Repository fltk/fltk, pull requests merged in 2020-07, with the labels that each got.

#102 add resize documentation as per STR3433
  documentation/Doxyfile.in
  documentation/Makefile
  documentation/src/common.dox
  documentation/src/drawing.dox
  documentation/src/editor.dox
  documentation/src/examples.dox
  documentation/src/faq.dox
  documentation/src/fluid.dox
  documentation/src/index.dox
  documentation/src/resize-example1.png
  documentation/src/resize-example2.png
  documentation/src/resize-example3a.png
  documentation/src/resize-example3b.png
  documentation/src/resize-example3c.png
  documentation/src/resize-example4a.png
  documentation/src/resize-example4b.png
  documentation/src/resize.dox
Labels: enhancement

#103 New PR for PR #99: Branch issue-99 rebased and edited
  FL/Fl_File_Browser.H
  FL/Fl_File_Chooser.H
  fluid/ExternalCodeEditor_WIN32.cxx
  fluid/fluid.cxx
  src/Fl_File_Browser.cxx
  src/Fl_File_Chooser.cxx
  src/Fl_File_Chooser.fl
  src/Fl_File_Chooser2.cxx
  src/Fl_System_Driver.H
  src/Fl_System_Driver.cxx
  src/drivers/Android/Fl_Android_System_Driver.H
  src/drivers/Android/Fl_Android_System_Driver.cxx
  src/drivers/Darwin/Fl_Darwin_System_Driver.H
  src/drivers/Darwin/Fl_Darwin_System_Driver.cxx
  src/drivers/WinAPI/Fl_WinAPI_System_Driver.H
  src/drivers/WinAPI/Fl_WinAPI_System_Driver.cxx
  src/drivers/X11/Fl_X11_System_Driver.H
  src/drivers/X11/Fl_X11_System_Driver.cxx
  src/filename_isdir.cxx
  src/filename_list.cxx
  src/scandir_posix.c
  src/scandir_win32.c
  test/file_chooser.cxx
  test/pixmap_browser.cxx
Labels: enhancement

#104 add resize examples as per STR3433
  test/CMakeLists.txt
  test/Makefile
  test/demo.menu
  test/resize-arrows.cxx
  test/resize-arrows.h
  test/resize-example1.cxx
  test/resize-example2.cxx
  test/resize-example3a.cxx
  test/resize-example3b.cxx
  test/resize-example3c.cxx
  test/resize-example4a.cxx
  test/resize-example4b.cxx
Labels: enhancement, fixed

#111 Simplify, clarify and fix bugs in test/demo.cxx
  test/CMakeLists.txt
  test/demo.cxx
  test/demo.menu
Labels: CMake, bug, enhancement, fixed
