Repository fltk/fltk, pull requests merged in 2023-01, with the labels that each got.

#621 Make sure that zlib and png are both local or system
  CMake/options.cmake
  configure.ac
Labels: active, Prio 2 - Low

#628 Add close buttons for individual tabs in Fl_Tabs
  CHANGES.txt
  FL/Enumerations.H
  FL/Fl.H
  FL/Fl_Browser_.H
  FL/Fl_Button.H
  FL/Fl_Color_Chooser.H
  FL/Fl_Group.H
  FL/Fl_Input_.H
  FL/Fl_Menu_Item.H
  FL/Fl_Tabs.H
  FL/Fl_Text_Editor.H
  FL/Fl_Tree.H
  FL/Fl_Widget.H
  FL/Fl_Window.H
  FL/names.h
  fluid/CodeEditor.cxx
  fluid/Fl_Widget_Type.cxx
  fluid/Shortcut_Button.cxx
  src/Fl.cxx
  src/Fl_Browser_.cxx
  src/Fl_Button.cxx
  src/Fl_Color_Chooser.cxx
  src/Fl_File_Input.cxx
  src/Fl_Help_View.cxx
  src/Fl_Input.cxx
  src/Fl_Input_.cxx
  src/Fl_Input_Choice.cxx
  src/Fl_Positioner.cxx
  src/Fl_Repeat_Button.cxx
  src/Fl_Return_Button.cxx
  src/Fl_Scrollbar.cxx
  src/Fl_Spinner.cxx
  src/Fl_Tabs.cxx
  src/Fl_Text_Editor.cxx
  src/Fl_Tile.cxx
  src/Fl_Tree.cxx
  src/Fl_Valuator.cxx
  src/Fl_Value_Input.cxx
  src/Fl_Widget.cxx
  test/browser.cxx
  test/tabs.fl
Labels: enhancement, active, RFC: request for comments

#636 X11: Optionally copy selection buffer to clipboard (STR 3229)
  FL/Fl.H
  src/Fl.cxx
  src/Fl_x.cxx
Labels: enhancement, fixed, Platform: X11, Prio 1 - RFE

#642 FLUID: add drag'n'drop for images
  fluid/Fl_Window_Type.cxx
  src/fl_utf8.cxx
Labels: fluid, Prio 1 - RFE

#560 Move global FLTK options into new app fltk-admin
  CMake/install.cmake
  CMake/options.cmake
  CMakeLists.txt
  Makefile
  README.CMake.txt
  configure.ac
  documentation/Doxyfile.in
  documentation/Makefile
  documentation/src/advanced.dox
  documentation/src/fltk-config.man
  documentation/src/fltk-options.dox
  documentation/src/fltk-options.man
  documentation/src/fluid.dox
  documentation/src/index.dox
  documentation/src/preface.dox
  fltk-options/CMakeLists.txt
  fltk-options/Makefile
  fltk-options/fltk-options.cxx
  fltk-options/fltk-options.desktop
  fltk-options/fltk-options.plist
  fltk-options/fltk-options.xml
  fltk-options/icons/fltk-options-128.png
  fltk-options/icons/fltk-options-16.png
  fltk-options/icons/fltk-options-16i.png
  fltk-options/icons/fltk-options-256.png
  fltk-options/icons/fltk-options-32.gif
  fltk-options/icons/fltk-options-32.png
  fltk-options/icons/fltk-options-32.xpm
  fltk-options/icons/fltk-options-32i.png
  fltk-options/icons/fltk-options-48.png
  fltk-options/icons/fltk-options-64.png
  fltk-options/icons/fltk-options-96.gif
  fltk-options/icons/fltk-options-96.xpm
  fltk-options/icons/fltk-options.icns
  fltk-options/icons/fltk-options.ico
  fltk-options/icons/fltk-options.xcf
  fltk-options/makedepend
  fltk.list.in
  fluid/Fl_Window_Type.cxx
  fluid/Fl_Window_Type.h
  fluid/alignment_panel.cxx
  fluid/alignment_panel.fl
  fluid/alignment_panel.h
  fluid/fluid.cxx
  makeinclude.in
  test/demo.cxx
  test/demo.menu
Labels: Prio 2 - Low
